import { SapMetadata } from '@/types/sap';

export const MOCK_SAP_METADATA_PURCHASE_ORDER: SapMetadata = {
  version: '2.0',
  namespace: 'API_PURCHASEORDER_PROCESS_SRV',
  fetchedAt: new Date().toISOString(),
  entitySets: [
    {
      name: 'A_PurchaseOrder',
      entityType: 'A_PurchaseOrderType',
      creatable: true,
      updatable: true,
      deletable: false,
      keyFields: ['PurchaseOrder'],
      fields: [
        { name: 'PurchaseOrder', label: 'Purchase Order', type: 'Edm.String', nullable: false, isKey: true, maxLength: 10 },
        { name: 'CompanyCode', label: 'Company Code', type: 'Edm.String', nullable: false, isKey: false, maxLength: 4 },
        { name: 'PurchaseOrderType', label: 'Order Type', type: 'Edm.String', nullable: false, isKey: false, maxLength: 4 },
        { name: 'Supplier', label: 'Supplier / Vendor', type: 'Edm.String', nullable: false, isKey: false, maxLength: 10 },
        { name: 'PurchaseOrderDate', label: 'Order Date', type: 'Edm.DateTime', nullable: true, isKey: false },
        { name: 'DocumentCurrency', label: 'Currency', type: 'Edm.String', nullable: true, isKey: false, maxLength: 5 },
        { name: 'PurchasingOrganization', label: 'Purchasing Org', type: 'Edm.String', nullable: true, isKey: false, maxLength: 4 },
        { name: 'PurchasingGroup', label: 'Purchasing Group', type: 'Edm.String', nullable: true, isKey: false, maxLength: 3 },
        { name: 'GrossAmount', label: 'Total Gross Amount', type: 'Edm.Decimal', nullable: true, isKey: false, precision: 15, scale: 2 },
        { name: 'Remarks', label: 'Header Text / Remarks', type: 'Edm.String', nullable: true, isKey: false, maxLength: 255 },
      ],
    },
    {
      name: 'A_PurchaseOrderItem',
      entityType: 'A_PurchaseOrderItemType',
      creatable: true,
      updatable: true,
      deletable: false,
      keyFields: ['PurchaseOrder', 'PurchaseOrderItem'],
      fields: [
        { name: 'PurchaseOrder', label: 'Purchase Order', type: 'Edm.String', nullable: false, isKey: true, maxLength: 10 },
        { name: 'PurchaseOrderItem', label: 'PO Item', type: 'Edm.String', nullable: false, isKey: true, maxLength: 5 },
        { name: 'Material', label: 'Material / Part No', type: 'Edm.String', nullable: false, isKey: false, maxLength: 40 },
        { name: 'PurchaseOrderItemText', label: 'Short Description', type: 'Edm.String', nullable: true, isKey: false, maxLength: 40 },
        { name: 'OrderQuantity', label: 'Order Quantity', type: 'Edm.Decimal', nullable: false, isKey: false, precision: 13, scale: 3 },
        { name: 'PurchaseOrderQuantityUnit', label: 'Order Unit', type: 'Edm.String', nullable: true, isKey: false, maxLength: 3 },
        { name: 'NetPriceAmount', label: 'Net Unit Price', type: 'Edm.Decimal', nullable: true, isKey: false, precision: 11, scale: 2 },
        { name: 'Plant', label: 'Plant', type: 'Edm.String', nullable: true, isKey: false, maxLength: 4 },
        { name: 'StorageLocation', label: 'Storage Location', type: 'Edm.String', nullable: true, isKey: false, maxLength: 4 },
        { name: 'Batch', label: 'Batch No', type: 'Edm.String', nullable: true, isKey: false, maxLength: 10 },
      ],
    },
    {
      name: 'ProductionOrderConfirmations',
      entityType: 'ProductionOrderConfirmationType',
      creatable: true,
      updatable: true,
      deletable: false,
      keyFields: ['ConfirmationNumber', 'ConfirmationCounter'],
      fields: [
        { name: 'ConfirmationNumber', label: 'Confirmation No', type: 'Edm.String', nullable: false, isKey: true, maxLength: 10 },
        { name: 'ConfirmationCounter', label: 'Counter', type: 'Edm.String', nullable: false, isKey: true, maxLength: 8 },
        { name: 'ManufacturingOrder', label: 'Prod Order No', type: 'Edm.String', nullable: false, isKey: false, maxLength: 12 },
        { name: 'Material', label: 'Part / Material No', type: 'Edm.String', nullable: false, isKey: false, maxLength: 40 },
        { name: 'MaterialDescription', label: 'Description', type: 'Edm.String', nullable: true, isKey: false, maxLength: 40 },
        { name: 'ConfirmedQuantity', label: 'Produced / Confirmed Qty', type: 'Edm.Decimal', nullable: false, isKey: false, precision: 13, scale: 3 },
        { name: 'ScrapQuantity', label: 'Rejection / Scrap Qty', type: 'Edm.Decimal', nullable: true, isKey: false, precision: 13, scale: 3 },
        { name: 'ConfirmationDate', label: 'Production Date', type: 'Edm.DateTime', nullable: false, isKey: false },
        { name: 'WorkShift', label: 'Shift (A, B, C)', type: 'Edm.String', nullable: true, isKey: false, maxLength: 10 },
        { name: 'Batch', label: 'Batch No', type: 'Edm.String', nullable: true, isKey: false, maxLength: 10 },
        { name: 'PersonnelNumber', label: 'Operator No', type: 'Edm.String', nullable: true, isKey: false, maxLength: 8 },
        { name: 'OpeningCounter', label: 'Opening Machine Counter', type: 'Edm.Int32', nullable: true, isKey: false },
        { name: 'ClosingCounter', label: 'Closing Machine Counter', type: 'Edm.Int32', nullable: true, isKey: false },
        { name: 'PurgeWeight', label: 'Purge Weight (g)', type: 'Edm.Decimal', nullable: true, isKey: false, precision: 9, scale: 2 },
        { name: 'RunnerWeight', label: 'Runner Weight (g)', type: 'Edm.Decimal', nullable: true, isKey: false, precision: 9, scale: 2 },
        { name: 'CavitiesCount', label: 'No of Cavities', type: 'Edm.Int32', nullable: true, isKey: false },
        { name: 'Remarks', label: 'Operator Remarks', type: 'Edm.String', nullable: true, isKey: false, maxLength: 255 },
      ],
    },
    {
      name: 'A_MaterialDocumentHeader',
      entityType: 'A_MaterialDocumentHeaderType',
      creatable: true,
      updatable: false,
      deletable: false,
      keyFields: ['MaterialDocument', 'MaterialDocumentYear'],
      fields: [
        { name: 'MaterialDocument', label: 'Material Document No', type: 'Edm.String', nullable: false, isKey: true, maxLength: 10 },
        { name: 'MaterialDocumentYear', label: 'Doc Year', type: 'Edm.String', nullable: false, isKey: true, maxLength: 4 },
        { name: 'DocumentDate', label: 'Document Date', type: 'Edm.DateTime', nullable: false, isKey: false },
        { name: 'PostingDate', label: 'Posting Date', type: 'Edm.DateTime', nullable: false, isKey: false },
        { name: 'ReferenceDocument', label: 'Reference / Invoice No', type: 'Edm.String', nullable: true, isKey: false, maxLength: 16 },
        { name: 'MaterialDocumentHeaderText', label: 'Header Text', type: 'Edm.String', nullable: true, isKey: false, maxLength: 25 },
      ],
    },
  ],
};
